# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import projetos_pb2 as projetos__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in projetos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProjetoServiceStub(object):
    """Define o nosso serviço. Pense nisso como a nossa "classe de API".
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListarProjetos = channel.unary_unary(
                '/projetos.ProjetoService/ListarProjetos',
                request_serializer=projetos__pb2.ListarProjetosRequest.SerializeToString,
                response_deserializer=projetos__pb2.ListarProjetosResponse.FromString,
                _registered_method=True)


class ProjetoServiceServicer(object):
    """Define o nosso serviço. Pense nisso como a nossa "classe de API".
    """

    def ListarProjetos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProjetoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListarProjetos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarProjetos,
                    request_deserializer=projetos__pb2.ListarProjetosRequest.FromString,
                    response_serializer=projetos__pb2.ListarProjetosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'projetos.ProjetoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('projetos.ProjetoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProjetoService(object):
    """Define o nosso serviço. Pense nisso como a nossa "classe de API".
    """

    @staticmethod
    def ListarProjetos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/projetos.ProjetoService/ListarProjetos',
            projetos__pb2.ListarProjetosRequest.SerializeToString,
            projetos__pb2.ListarProjetosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
