# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: projetos.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'projetos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprojetos.proto\x12\x08projetos\"\x17\n\x15ListarProjetosRequest\"\'\n\x07Usuario\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\"]\n\x07Projeto\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\"\n\x07members\x18\x04 \x03(\x0b\x32\x11.projetos.Usuario\"=\n\x16ListarProjetosResponse\x12#\n\x08projetos\x18\x01 \x03(\x0b\x32\x11.projetos.Projeto2e\n\x0eProjetoService\x12S\n\x0eListarProjetos\x12\x1f.projetos.ListarProjetosRequest\x1a .projetos.ListarProjetosResponseB\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'projetos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_LISTARPROJETOSREQUEST']._serialized_start=28
  _globals['_LISTARPROJETOSREQUEST']._serialized_end=51
  _globals['_USUARIO']._serialized_start=53
  _globals['_USUARIO']._serialized_end=92
  _globals['_PROJETO']._serialized_start=94
  _globals['_PROJETO']._serialized_end=187
  _globals['_LISTARPROJETOSRESPONSE']._serialized_start=189
  _globals['_LISTARPROJETOSRESPONSE']._serialized_end=250
  _globals['_PROJETOSERVICE']._serialized_start=252
  _globals['_PROJETOSERVICE']._serialized_end=353
# @@protoc_insertion_point(module_scope)
